wandb:
  project: Traj_transformer
  entity: 'x-huang'
  group: 'TrajTransformer'
  name: '1107-1-512-reg-4'

train:
  batch_size: 512
  epochs: 100
  warmup_epochs: 40
  lr: 0.0001
  lr_scheduler:
    type: 'stepLR'
    step_size: 10
    gamma: 0.1
  wd: 0.00001
  device: 'cuda:0'

model:
  mp:
    mlp:
      in_dim: 256
      hidden_dim: 256
      n_layer: 1
  transformer:
    n_layer: 4
    n_head: 8
    emb_dim: 256
    dropout: 0.1
    register_tokens: 4