wandb:
  project: Traj_transformer
  entity: 'x-huang'
  group: 'TrajTransformer'
  name: '1108-adamW'

train:
  batch_size: 256
  epochs: 100
  warmup_epochs: 0
  lr: 0.001
  lr_scheduler:
    step_size: 10
    gamma: 0.1
  lr_decay: 0.1
  wd: 1e-04
  device: 'cuda:1'

model:
  mp:
    mlp:
      in_dim: 256
      hidden_dim: 256
      n_layer: 1
  transformer:
    n_layer: 4
    n_head: 8
    emb_dim: 256
    dropout: 0.1