wandb:
  project: Traj_transformer
  entity: 'x-huang'
  group: 'Debug'
  name: 'mac'

train:
  batch_size: 512
  epochs: 1
  n_checkpoints: 1
  warmup_epochs: 20
  lr: 0.001
  lr_scheduler:
    step_size: 10
    gamma: 0.1
  lr_decay: 0.1
  wd: 0.00001
  device: 'cpu'

model:
  mp:
    mlp:
      in_dim: 256
      hidden_dim: 256
      n_layer: 1
  transformer:
    input_type: 'extend'
    pre_mlp_input_dim: 18
    post_mlp_output_dim: 256
    n_layer: 4
    n_head: 8
    emb_dim: 256
    dropout: 0.1
    register_tokens: 4